Repository omgnetwork/omg-childchain-v1, pull requests merged in 2020-11, with the labels that each got.

#25 feat: send web telemetry events to Datadog
  apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/controllers/fallback.ex
  apps/omg_status/README.md
  apps/omg_status/lib/omg_status/application.ex
  apps/omg_status/lib/omg_status/configuration.ex
  apps/omg_status/lib/omg_status/metric/telemetry.ex
  apps/omg_status/mix.exs
  mix.lock
Labels: enhancement

#26 cleanup makefile && filter nonce errors on Sentry
  Makefile
  apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/endpoint.ex
  apps/omg_status/lib/omg_status/sentry_filter.ex
  apps/omg_status/mix.exs
  mix.lock
Labels: enhancement

#28 apply sentry filter module
  config/config.exs
Labels: bug

#30 Add remote ip plug
  apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/endpoint.ex
  apps/omg_utils/lib/omg_utils/remote_ip.ex
  apps/omg_utils/test/omg_utils/http_rpc/remote_ip_test.exs
Labels: chore

#32 fix: set service name as a tag in metrics
  apps/omg_status/lib/omg_status/metric/telemetry.ex
Labels: chore

#27 simplification of event pulling
  .circleci/config.yml
  apps/omg/lib/omg/ethereum_event_listener.ex
  apps/omg/lib/omg/ethereum_event_listener/core.ex
  apps/omg/lib/omg/state.ex
  apps/omg/test/omg/ethereum_event_listener/core_test.exs
  apps/omg/test/omg/state/transaction/recovered_test.exs
  apps/omg/test/omg/state/utxo_set_test.exs
  apps/omg/test/omg/state_test.exs
  apps/omg/test/support/integration/deposit_helper.ex
  apps/omg/test/support/test_helper.ex
  apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex
  apps/omg_child_chain/lib/omg_child_chain/ethereum_event_aggregator.ex
  apps/omg_child_chain/test/omg_child_chain/block_queue/core_test.exs
  apps/omg_child_chain/test/omg_child_chain/ethereum_event_aggregator_test.exs
  apps/omg_eth/test/support/dev_geth.ex
  apps/omg_utils/lib/omg_utils/http_rpc/validators/base.ex
  docker-compose.yml
  docker/geth/command
  docker/geth/geth-blank-password
Labels: chore
